[general]
password_general = "CARTERAFERREINOX"

[vendedores]
"TANIA RESTREPO BENJUMEA" = "18452"
"LEDUYN MELGAREJO ARIAS" = "29513"
"PABLO CESAR MAFLA BAÑOL" = "37041"
"HUGO NELSON ZAPATA RAYO" = "48290"
"RICHARD RAFAEL FERRER ROZO" = "59328"
"ELISABETH IBARRA M." = "60417"
"JULIAN MAURICIO ORTIZ GOMEZ" = "71536"
"CARLOS ALBERTO CASTRILLON LOPEZ" = "82645"
"PEREZ SANTA GUSTAVO ADOLFO" = "14829"
# Los siguientes nombres no tienen código asignado en tu lista original:
"COMERCIAL FERREINOX" = ""
"JAIME ANDRES LONDOÑO MONTENEGRO" = ""
"LEIVYN GRABIEL GARCIA MUÑOZ" = ""
"JOSE AURELIO MARTINEZ ROJAS" = ""
