[general]
password = "CARTERAFERREINOX"

[vendedores]
TANIA_RESTREPO_BENJUMEA = "18452"
LEDUYN = "29513"
PABLO = "37041"
HUGO = "48290"
RICHARD = "59328"
ELISABETH = "60417"
JULIAN = "71536"
CARLOS = "82645"
GUSTAVO = "93754"
PEREZ_SANTA = "14829"
